# File generated by Flopy version 3.10.0.dev5 on 01/30/2026 at 12:54:03.
BEGIN attributes
  NAMES  rch_3
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00170000
       1.00000000       0.00200000
      11.00000000       0.00170000
      21.00000000       0.00180000
      31.00000000       0.00200000
END timeseries

