name: hydro_sim2real
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pip